name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - name: Test
        run: bazelisk test //test/...
      - name: Test Package dSYM
        run: bazelisk test --apple_generate_dsym --output_groups=+dsyms //test:pkg_dsym_build_test
  buildifier:
    name: Run Buildifier and Verify Documentation Generation
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - run: make buildifier
      - run: make docs
